select * from [dbo].[planteles_20142_20182];

select *
from [dbo].[planteles_20142_20182]
where COLE_INST_NOMBRE='COLEGIO ALTAMIRA';

select COLE_DEPTO_COLEGIO, COUNT(*) AS 'COUNT', AVG(INDICE_C_NATURALES) AS 'AVG(INDICE_C_NATURALES)', AVG(INDICE_MATEMATICAS) AS 'AVG(INDICE_MATEMATICAS)', 
		AVG(INDICE_SOCIALES_CIUDADANAS) AS 'AVG(INDICE_SOCIALES_CIUDADANAS)', AVG(INDICE_LECTURA_CRITICA) AS 'AVG(INDICE_LECTURA_CRITICA)', 
		AVG(INDICE_INGLES) AS 'AVG(INDICE_INGLES)', AVG(INDICE_TOTAL) AS 'AVG(INDICE_TOTAL)'
from [dbo].[planteles_20142_20182]
where YEAR=2018
group by COLE_DEPTO_COLEGIO
order by 1;


select COLE_DEPTO_COLEGIO, COLE_MPIO_MUNICIPIO, COUNT(*) AS 'COUNT', AVG(INDICE_C_NATURALES) AS 'AVG(INDICE_C_NATURALES)', AVG(INDICE_MATEMATICAS) AS 'AVG(INDICE_MATEMATICAS)', 
		AVG(INDICE_SOCIALES_CIUDADANAS) AS 'AVG(INDICE_SOCIALES_CIUDADANAS)', AVG(INDICE_LECTURA_CRITICA) AS 'AVG(INDICE_LECTURA_CRITICA)', 
		AVG(INDICE_INGLES) AS 'AVG(INDICE_INGLES)', AVG(INDICE_TOTAL) AS 'AVG(INDICE_TOTAL)'
from [dbo].[planteles_20142_20182]
where YEAR=2018
group by COLE_DEPTO_COLEGIO, COLE_MPIO_MUNICIPIO
order by 1,2;

select * 
from [dbo].[VW_MODULOIII_DOCENTESESCALFO];

select GRADOESCA_CODIGO, count(*) as 'COUNT'
from [dbo].[VW_MODULOIII_DOCENTESESCALFO]
where PERIODO_ANIO = 2018
group by GRADOESCA_CODIGO;




select * 
from [dbo].[VW_MODULOIII_DOCENTESESCALFO]
where SEDE_CODIGO = 308001074789
-- and PERIODO_ANIO = 2018
;

select * 
from [dbo].[VW_MODULOIII_DOCENTESESCALFO]
where SEDE_CODIGO = 308001074789
and PERIODO_ANIO in (2018, 2017)
;

select GRADOESCA_NOMBRE, COUNT(*) as 'COUNT'
from [dbo].[VW_MODULOIII_DOCENTESESCALFO]
group by GRADOESCA_NOMBRE
order by 2 desc;

--where SEDE_CODIGO = 308001074789
--and PERIODO_ANIO = 2018

select *
from
(
	select SEDE_CODIGO, PERIODO_ANIO, GRADOESCA_NOMBRE, SEDEDOES_CANTIDAD_MUJER 
	from [dbo].[VW_MODULOIII_DOCENTESESCALFO]
	where SEDE_CODIGO = 308001074789
	and PERIODO_ANIO in (2018, 2017)
) src
pivot
(
	sum(SEDEDOES_CANTIDAD_MUJER)
	for GRADOESCA_NOMBRE in ([Grado 1],[Grado 4],[Grado 5])
) piv;
